variables:
  GITLAB_VERSION: "master"
  GITLAB_SHELL_VERSION: "master"
  GITALY_VERSION: "master"

stages:
  - base-container
  - common-container
  - target-container

gitlab-ruby:
  stage: base-container
  image: "registry.gitlab.com/gitlab-org/gitlab-omnibus-builder:ruby_docker-0.0.7"
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  services:
  - docker:dind
  script:
  - CONTAINER_VERSION=$(git ls-tree HEAD -- ruby | awk '{ print $3 }')
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  # Build container if it doesn't exist
  - if ! $(docker pull "$CI_REGISTRY_IMAGE/gitlab-ruby:$CONTAINER_VERSION" > /dev/null); then
  # Pull the existing image to reuse existing layers
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-ruby:latest" || true
  -   cd ruby
  -   docker build -t "$CI_REGISTRY_IMAGE/gitlab-ruby:$CONTAINER_VERSION" --cache-from "$CI_REGISTRY_IMAGE/gitlab-rails:latest" .
  #   Push new image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-ruby:$CONTAINER_VERSION"
  #   Create a tag based on Branch/Tag name for easy reference
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-ruby:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-ruby:$CI_COMMIT_REF_SLUG"
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-ruby:$CI_COMMIT_REF_SLUG"
  - fi
  # Push the latest tag if master
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-ruby:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-ruby:latest"
  #   Push latest image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-ruby:latest"
  - fi
  dependencies: []
  retry: 1

gitlab-rails:
  stage: common-container
  image: "registry.gitlab.com/gitlab-org/gitlab-omnibus-builder:ruby_docker-0.0.7"
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  services:
  - docker:dind
  script:
  - BASE_VERSION=$(git ls-tree HEAD -- ruby | awk '{ print $3 }')
  - TARGET_VERSION=$(git ls-tree HEAD -- rails | awk '{ print $3 }')
  - CONTAINER_VERSION=($(echo -n "$BASE_VERSION$TARGET_VERSION" | sha1sum))
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  # Build container if it doesn't exist
  - if [ -n "$NIGHTLY" ] || ! $(docker pull "$CI_REGISTRY_IMAGE/gitlab-rails:$CONTAINER_VERSION" > /dev/null); then
  #   Pull the base image
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-ruby:$BASE_VERSION"
  # Pull the existing image to reuse existing layers
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-rails:latest" || true
  -   cd rails
  -   docker build --build-arg "TAG=$BASE_VERSION" --build-arg "GITLAB_VERSION=${GITLAB_VERSION}" --build-arg "CACHE_BUSTER=$(date -uI)" -t "$CI_REGISTRY_IMAGE/gitlab-rails:$CONTAINER_VERSION" --cache-from "$CI_REGISTRY_IMAGE/gitlab-rails:latest" .
  #   Push new image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-rails:$CONTAINER_VERSION"
  #   Create a tag based on Branch/Tag name for easy reference
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-rails:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-rails:$CI_COMMIT_REF_SLUG"
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-rails:$CI_COMMIT_REF_SLUG"
  - fi
  # Push the latest tag if master
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-rails:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-rails:latest"
  #   Push latest image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-rails:latest"
  - fi
  dependencies: []
  retry: 1

unicorn:
  stage: target-container
  image: "registry.gitlab.com/gitlab-org/gitlab-omnibus-builder:ruby_docker-0.0.7"
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  services:
  - docker:dind
  script:
  - BASE_VERSION=$(git ls-tree HEAD -- ruby | awk '{ print $3 }')
  - RAILS_VERSION=$(git ls-tree HEAD -- rails | awk '{ print $3 }')
  - UNICORN_VERSION=$(git ls-tree HEAD -- unicorn | awk '{ print $3 }')
  - RAILS_CONTAINER=($(echo -n "$BASE_VERSION$RAILS_VERSION" | sha1sum))
  - CONTAINER_VERSION=($(echo -n "$RAILS_CONTAINER$UNICORN_VERSION" | sha1sum))
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  # Build container if it doesn't exist
  - if [ -n "$NIGHTLY" ] || ! $(docker pull "$CI_REGISTRY_IMAGE/gitlab-unicorn:$CONTAINER_VERSION" > /dev/null); then
  #   Pull the rails image
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-rails:$RAILS_CONTAINER"
  #   Pull the existing image to reuse existing layers
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-unicorn:latest" || true
  #   Build new image
  -   cd unicorn
  -   docker build --build-arg "TAG=$RAILS_CONTAINER" --build-arg "GITLAB_VERSION=${GITLAB_VERSION}" -t "$CI_REGISTRY_IMAGE/gitlab-unicorn:$CONTAINER_VERSION" --cache-from "$CI_REGISTRY_IMAGE/gitlab-unicorn:latest" .
  #   Push new image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-unicorn:$CONTAINER_VERSION"
  #   Create a tag based on Branch/Tag name for easy reference
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-unicorn:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-unicorn:$CI_COMMIT_REF_SLUG"
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-unicorn:$CI_COMMIT_REF_SLUG"
  - fi
  # Push the latest tag if master
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-unicorn:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-unicorn:latest"
  #   Push latest image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-unicorn:latest"
  - fi
  dependencies:
    - gitlab-rails
  retry: 1

sidekiq:
  stage: target-container
  image: "registry.gitlab.com/gitlab-org/gitlab-omnibus-builder:ruby_docker-0.0.7"
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  services:
  - docker:dind
  script:
  - BASE_VERSION=$(git ls-tree HEAD -- ruby | awk '{ print $3 }')
  - RAILS_VERSION=$(git ls-tree HEAD -- rails | awk '{ print $3 }')
  - SIDEKIQ_VERSION=$(git ls-tree HEAD -- sidekiq | awk '{ print $3 }')
  - RAILS_CONTAINER=($(echo -n "$BASE_VERSION$RAILS_VERSION" | sha1sum))
  - CONTAINER_VERSION=($(echo -n "$RAILS_CONTAINER$SIDEKIQ_VERSION" | sha1sum))
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  # Build container if it doesn't exist
  - if [ -n "$NIGHTLY" ] || ! $(docker pull "$CI_REGISTRY_IMAGE/gitlab-sidekiq:$CONTAINER_VERSION" > /dev/null); then
  #   Pull the rails image
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-rails:$RAILS_CONTAINER"
  # Pull the existing image to reuse existing layers
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-sidekiq:latest" || true
  #   Build new image
  -   cd sidekiq
  -   docker build --build-arg "TAG=$RAILS_CONTAINER" --build-arg "GITLAB_VERSION=${GITLAB_VERSION}" -t "$CI_REGISTRY_IMAGE/gitlab-sidekiq:$CONTAINER_VERSION" --cache-from "$CI_REGISTRY_IMAGE/gitlab-sidekiq:latest" .
  #   Push new image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-sidekiq:$CONTAINER_VERSION"
  #   Create a tag based on Branch/Tag name for easy reference
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-sidekiq:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-sidekiq:$CI_COMMIT_REF_SLUG"
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-sidekiq:$CI_COMMIT_REF_SLUG"
  - fi
  # Push the latest tag if master
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-sidekiq:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-sidekiq:latest"
  #   Push latest image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-sidekiq:latest"
  - fi
  dependencies:
    - gitlab-rails
  retry: 1

shell:
  stage: common-container
  image: "registry.gitlab.com/gitlab-org/gitlab-omnibus-builder:ruby_docker-0.0.7"
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  services:
  - docker:dind
  script:
  - BASE_VERSION=$(git ls-tree HEAD -- ruby | awk '{ print $3 }')
  - TARGET_VERSION=$(git ls-tree HEAD -- shell | awk '{ print $3 }')
  - CONTAINER_VERSION=($(echo -n "$BASE_VERSION$TARGET_VERSION" | sha1sum))
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  # Build container if it doesn't exist
  - if [ -n "$NIGHTLY" ] || ! $(docker pull "$CI_REGISTRY_IMAGE/gitlab-shell:$CONTAINER_VERSION" > /dev/null); then
  #   Pull the base image
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-ruby:$BASE_VERSION"
  #   Pull the existing image to reuse existing layers
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-shell:latest" || true
  #   Build new image
  -   cd shell
  -   docker build --build-arg "TAG=$BASE_VERSION" --build-arg "GITLAB_SHELL_VERSION=${GITLAB_SHELL_VERSION}" --build-arg "CACHE_BUSTER=$(date -uI)" -t "$CI_REGISTRY_IMAGE/gitlab-shell:$CONTAINER_VERSION" --cache-from "$CI_REGISTRY_IMAGE/gitlab-shell:latest" .
  #   Push new image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-shell:$CONTAINER_VERSION"
  #   Create a tag based on Branch/Tag name for easy reference
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-shell:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-shell:$CI_COMMIT_REF_SLUG"
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-shell:$CI_COMMIT_REF_SLUG"
  - fi
  # Push the latest tag if master
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
  -   docker tag "$CI_REGISTRY_IMAGE/gitlab-shell:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitlab-shell:latest"
  #   Push latest image
  -   docker push "$CI_REGISTRY_IMAGE/gitlab-shell:latest"
  - fi
  dependencies:
    - gitlab-ruby
  retry: 1

gitaly:
  stage: target-container
  image: "registry.gitlab.com/gitlab-org/gitlab-omnibus-builder:ruby_docker-0.0.7"
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  services:
  - docker:dind
  script:
  - BASE_VERSION=$(git ls-tree HEAD -- ruby | awk '{ print $3 }')
  - TARGET_VERSION=$(git ls-tree HEAD -- gitaly | awk '{ print $3 }')
  - SHELL_VERSION=$(git ls-tree HEAD -- shell | awk '{ print $3 }')
  - SHELL_CONTAINER=($(echo -n "$BASE_VERSION$SHELL_VERSION" | sha1sum))
  - CONTAINER_VERSION=($(echo -n "$SHELL_CONTAINER$TARGET_VERSION" | sha1sum))
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  # Build container if it doesn't exist
  - if [ -n "$NIGHTLY" ] || ! $(docker pull "$CI_REGISTRY_IMAGE/gitaly:$CONTAINER_VERSION" > /dev/null); then
  #   Pull the dependant images
  -   docker pull "$CI_REGISTRY_IMAGE/gitlab-shell:$SHELL_CONTAINER"
  #   Pull the existing image to reuse existing layers
  -   docker pull "$CI_REGISTRY_IMAGE/gitaly:latest" || true
  #   Build new image
  -   cd gitaly
  -   docker build --build-arg "GITALY_VERSION=${GITALY_VERSION}" --build-arg "TAG=$BASE_VERSION" --build-arg "SHELL_CONTAINER=$SHELL_CONTAINER" --build-arg "CACHE_BUSTER=$(date -uI)" -t "$CI_REGISTRY_IMAGE/gitaly:$CONTAINER_VERSION" --cache-from "$CI_REGISTRY_IMAGE/gitaly:latest" .
  #   Push new image
  -   docker push "$CI_REGISTRY_IMAGE/gitaly:$CONTAINER_VERSION"
  #   Create a tag based on Branch/Tag name for easy reference
  -   docker tag "$CI_REGISTRY_IMAGE/gitaly:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitaly:$CI_COMMIT_REF_SLUG"
  -   docker push "$CI_REGISTRY_IMAGE/gitaly:$CI_COMMIT_REF_SLUG"
  - fi
  # Push the latest tag if master
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
  -   docker tag "$CI_REGISTRY_IMAGE/gitaly:$CONTAINER_VERSION" "$CI_REGISTRY_IMAGE/gitaly:latest"
  #   Push latest image
  -   docker push "$CI_REGISTRY_IMAGE/gitaly:latest"
  - fi
  dependencies:
    - gitlab-ruby
    - shell
  retry: 1
