version: "3"
services:
  omnibus:
    image: ${GITLAB_OMNIBUS_IMAGE}
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
    - ./dev/omnibus-config/gitlab.rb:/etc/gitlab/gitlab.rb
    - db-upgrade:/tmp/db-upgrade
  migrations:
    image: ${GITLAB_RAILS_IMAGE}
    environment:
      - "CONFIG_TEMPLATE_DIRECTORY=/var/opt/gitlab/config/templates"
      - "CONFIG_DIRECTORY=/srv/gitlab/config"
      - "BYPASS_SCHEMA_VERSION=true"
    command: ["/scripts/wait-for-deps", "/scripts/db-migrate"]
    depends_on:
      - omnibus
    volumes:
      - ./dev/webservice-config:/var/opt/gitlab/config/templates
      - ./dev/shell-secret:/var/opt/gitlab/config/secrets
      - db-upgrade:/var/opt/gitlab/.upgrade-status
  webservice:
    image: ${GITLAB_WEBSERVICE_IMAGE}
    environment:
      - "GITLAB_HOST=localhost"
      - "GITLAB_PORT=${NGINX_HOST_PORT}"
      - "GITLAB_SSH_PORT=${SSH_HOST_PORT}"
      - "GITALY_FEATURE_DEFAULT_ON=1"
      - "CONFIG_TEMPLATE_DIRECTORY=/var/opt/gitlab/config/templates"
      - "CONFIG_DIRECTORY=/srv/gitlab/config"
    command: ["/scripts/wait-for-deps", "/scripts/process-wrapper"]
    depends_on:
      - omnibus
    ports:
      - "${WEBSERVICE_HOST_PORT}:8080"
    volumes:
      - ./dev/webservice-config:/var/opt/gitlab/config/templates
      - ./dev/shell-secret:/var/opt/gitlab/config/secrets
      - ./dev/workhorse-config/.gitlab_workhorse_secret:/srv/gitlab/.gitlab_workhorse_secret
      - uploads:/srv/gitlab/public/uploads
  actioncable:
    image: ${GITLAB_ACTIONCABLE_IMAGE}
    environment:
      - "GITLAB_HOST=omnibus"
      - "GITLAB_PORT=${NGINX_HOST_PORT}"
      - "GITLAB_SSH_PORT=${SSH_HOST_PORT}"
      - "GITALY_FEATURE_DEFAULT_ON=1"
      - "CONFIG_TEMPLATE_DIRECTORY=/var/opt/gitlab/config/templates"
      - "CONFIG_DIRECTORY=/srv/gitlab/config"
    command: ["/scripts/wait-for-deps", "/scripts/process-wrapper"]
    depends_on:
      - omnibus
    ports:
      - "${ACTIONCABLE_HOST_PORT}:8280"
    volumes:
      - ./dev/actioncable-config:/var/opt/gitlab/config/templates
      - ./dev/shell-secret:/var/opt/gitlab/config/secrets
      - ./dev/workhorse-config/.gitlab_workhorse_secret:/srv/gitlab/.gitlab_workhorse_secret
      - uploads:/srv/gitlab/public/uploads
  workhorse:
    image: ${GITLAB_WORKHORSE_IMAGE}
    environment:
      - "CONFIG_TEMPLATE_DIRECTORY=/var/opt/gitlab/config/templates"
      - "CONFIG_DIRECTORY=/srv/gitlab/config"
      - "GITLAB_WORKHORSE_EXTRA_ARGS=-authBackend http://webservice:8080 -cableBackend http://actioncable:8280"
    command: ["/scripts/start-workhorse"]
    depends_on:
      - webservice
    ports:
      - "${WORKHORSE_HOST_PORT}:8181"
    volumes:
      - ./dev/workhorse-config:/var/opt/gitlab/config/templates
      - ./dev/workhorse-config/.gitlab_workhorse_secret:/etc/gitlab/gitlab-workhorse/secret
      - uploads:/srv/gitlab/public/uploads
  sidekiq:
    image: ${GITLAB_SIDEKIQ_IMAGE}
    command: ["/scripts/wait-for-deps", "/scripts/process-wrapper"]
    depends_on:
      - omnibus
    environment:
      - "GITLAB_HOST=localhost"
      - "GITLAB_PORT=${NGINX_HOST_PORT}"
      - "GITALY_FEATURE_DEFAULT_ON=1"
      - "CONFIG_TEMPLATE_DIRECTORY=/var/opt/gitlab/config/templates"
      - "CONFIG_DIRECTORY=/srv/gitlab/config"
    volumes:
      - ./dev/sidekiq-config:/var/opt/gitlab/config/templates
  shell:
    image: ${GITLAB_SHELL_IMAGE}
    environment:
      - "CONFIG_TEMPLATE_DIRECTORY=/srv/gitlab-config"
      - "CONFIG_DIRECTORY=/srv/gitlab-shell"
    ports:
      - "${SSH_HOST_PORT}:2222"
    volumes:
      - ./dev/shell-config:/srv/gitlab-config
      - ./dev/shell-secret:/srv/gitlab-secrets
  gitaly:
    image: ${GITLAB_GITALY_IMAGE}
    ports:
      - "${GITALY_HOST_PORT}:8075"
    volumes:
      - ./dev/gitaly-config:/etc/gitaly
volumes:
  db-upgrade:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=10M"
  uploads:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=100M"
