version: "3"
services:
  omnibus:
    image: gitlab/gitlab-ee:latest
    volumes:
    - ./dev/omnibus-config/gitlab.rb:/etc/gitlab/gitlab.rb
  unicorn:
    image: gitlab-unicorn:10-0-stable-base-ee
    depends_on:
      - omnibus
    user: git
    ports:
      - "${UNICORN_HOST_PORT}:8080"
    volumes:
      - ./dev/unicorn-config:/var/opt/gitlab/config/gitlab
